package gui

import (
	"fmt"
	"testing"
)

func TestColumn(t *testing.T) {
	c := NewColumn("test", Position_Left_Up)
	c.Adjust(20)
	fmt.Println("Left Up")
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Left Down")
	c = NewColumn("test", Position_Left_Down)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Left")
	c = NewColumn("test", Position_Left)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Right")
	c = NewColumn("test", Position_Right)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Right Up")
	c = NewColumn("test", Position_Right_Up)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Right Down")
	c = NewColumn("test", Position_Right_Down)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Center")
	c = NewColumn("test", Position_Center)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Up")
	c = NewColumn("test", Position_Up)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
	fmt.Println("Down")
	c = NewColumn("test", Position_Down)
	fmt.Println(c.UpBorder())
	fmt.Println(c.Text())
	fmt.Println(c.DownBorder())
}
